spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: create


  data:
    redis:
      port: '6379'
      host: localhost
  h2:
    console:
      enabled: true

jwt:
  token:
    access-token-expire-time: 10000
    refresh-token-expire-time: 20000
    security-key: security-key-enough-for-line-this-is-security-key-this-is-security-key
