spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  jpa:
    database: mysql
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      port: '6379'
      host: localhost

jwt:
  token:
    access-token-expire-time: 300000
    refresh-token-expire-time: 300000
    security-key: security-key-enough-for-line-this-is-security-key-this-is-security-key
